pipeline:
  tests:
    image: node:9
    when:
      event: push
    environment:
      - NODE_ENV=test
      - PG_URL=postgresql://abacash:@database/abacash
    secrets: [ segment_write_key ]
    commands:
      - yarn
      - yarn test
      - yarn lint
      - yarn build

  docker:
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
    repo: abakus/abacash-api
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=abacash
