pipeline:
  tests:
    image: node:6
    when:
      event: push
    environment:
      - NODE_ENV=test
    commands:
      - npm install -g yarn
      - yarn

      - yarn test -- --timeout 0
      - yarn run lint
      - yarn coverage

  docker:
    image: plugins/docker
    when:
      event: tag
    repo: abakus/abacash-api
    tags:
      - ${DRONE_TAG##v}
      - latest

  slack:
    image: plugins/slack
    when:
      status: [ success, failure ]
      event: [ push, tag ]
    channel: abacash

services:
  database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=abacash
